name: Build and Release v2dat

on:
  push:
    branches: [main, master]
  # 监听release创建事件，注意types英文为 created
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Build statically linked binary
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o v2dat -ldflags="-s -w -extldflags '-static'" ./main.go

    - name: Verify binary
      run: file v2dat

    - name: Publish to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest   # 指定发布的标签为 latest
        files: v2dat
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
