name: Build v2dat static binary

on:
  push:
    branches: [ main, master ]
  release:
    types: [创建]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # 可根据需要调整

    - name: Build statically linked binary
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o v2dat \
          -ldflags="-s -w -extldflags '-static'" ./cmd/v2dat

    - name: Verify binary
      run: file v2dat

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: v2dat-linux-amd64
        path: v2dat
